"""Agregar tienda activa al usuario

Revision ID: 8af3f365ac1f
Revises: fb0b352444bd
Create Date: 2026-07-09 20:28:28.978370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af3f365ac1f'
down_revision: Union[str, Sequence[str], None] = 'fb0b352444bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('tienda_activa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'tiendas', ['tienda_activa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'tienda_activa_id')
    # ### end Alembic commands ###
