"""Eliminar tienda activa

Revision ID: b289d3db3ac9
Revises: 8af3f365ac1f
Create Date: 2026-07-09 21:13:11.422487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b289d3db3ac9'
down_revision: Union[str, Sequence[str], None] = '8af3f365ac1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('usuarios_tienda_activa_id_fkey'), 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'tienda_activa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('tienda_activa_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('usuarios_tienda_activa_id_fkey'), 'usuarios', 'tiendas', ['tienda_activa_id'], ['id'])
    # ### end Alembic commands ###
